from .blend import Blend
from .cutblur import CutBlur
from .cutmix import CutMix
from .cutmixup import CutMixup
from .cutout import Cutout
from .identity import Identity
from .mixup import Mixup
from .oneof import OneOf
from .rgb_permutation import RGBPermutation